troiswa_back_homepage:
    path:     /hello/{name}
    defaults: { _controller: TroiswaBackBundle:Default:index }

troiswa_back_page_contact:
    path:     /contact
    defaults: { _controller: TroiswaBackBundle:Main:contact }

troiswa_back_page_apropos:
    path:     /propos
    defaults: { _controller: TroiswaBackBundle:Main:propos }


troiswa_back_page_about:
    path:     /about
    defaults: { _controller: TroiswaBackBundle:Main:about }

troiswa_back_page_products:
    path:     /produit/test
    defaults: { _controller: TroiswaBackBundle:Produit:test }

troiswa_back_page_show:
    path:     /produit/{id}
    defaults: { _controller: TroiswaBackBundle:Produit:show }

troiswa_back_page_etudiant:
    path:     /etudiant/{prenom}/{nom}
    defaults: { _controller: TroiswaBackBundle:Main:etudiant }

troiswa_back_page_categorie:
    path:     /categorie
    defaults: { _controller: TroiswaBackBundle:Categorie:index }


troiswa_back_page_categoriedetail:
    path:     /categoriedetail/{id}
    defaults: { _controller: TroiswaBackBundle:Categorie:show }

troiswa_back_page_bo:
    path:     /
    defaults: { _controller: TroiswaBackBundle:Main:admin }
