troiswa_back_tags:
    resource: "@TroiswaBackBundle/Resources/config/routing/tags.yml"
    prefix:   /tags

troiswa_back_marque:
    resource: "@TroiswaBackBundle/Resources/config/routing/marque.yml"
    prefix:   /marque

# -------------------- ROUTE DE TEST --------------------
troiswa_back_homepage:
    path:     /hello/{name}
    defaults: { _controller: TroiswaBackBundle:Default:index }

troiswa_back_page_apropos:
    path:     /propos
    defaults: { _controller: TroiswaBackBundle:Main:propos }

troiswa_back_page_about:
    path:     /about
    defaults: { _controller: TroiswaBackBundle:Main:about }

troiswa_back_page_products:
    path:     /produit/test
    defaults: { _controller: TroiswaBackBundle:Produit:test }

troiswa_back_page_etudiant:
    path:     /etudiant/{prenom}/{nom}
    defaults: { _controller: TroiswaBackBundle:Main:etudiant }

# -------------------- FIN DES ROUTES DE TEST --------------------

troiswa_back_ressource_produit:
    resource: "@TroiswaBackBundle/Resources/config/Routing/produit.yml"
    prefix:   /

troiswa_back_ressource_categorie:
    resource: "@TroiswaBackBundle/Resources/config/Routing/categorie.yml"
    prefix:   /

troiswa_back_ressource_commentaire:
    resource: "@TroiswaBackBundle/Resources/config/Routing/commentaire.yml"
    prefix:   /

troiswa_back_page_bo:
    path:     /
    defaults: { _controller: TroiswaBackBundle:Main:admin }

troiswa_back_page_feedback:
    path:     /feedback
    defaults: { _controller: TroiswaBackBundle:Main:feedback }

troiswa_back_page_contact:
    path:     /contact
    defaults: { _controller: TroiswaBackBundle:Main:contact }




troiswa_back_page_categorie:
    path:     /categorie
    defaults: { _controller: TroiswaBackBundle:Categorie:index }

troiswa_back_page_categoriedetail:
    path:     /categoriedetail/{id}
    defaults: { _controller: TroiswaBackBundle:Categorie:show }



troiswa_back_page_panier:
    path:     /panier
    defaults: { _controller: TroiswaBackBundle:Cart:panier }


troiswa_back_page_panier_ajout:
    path:     /panier/add/{id}
    defaults: { _controller: TroiswaBackBundle:Cart:add }


troiswa_back_page_panier_delete:
    path:     /panier/supprimer/{id}
    defaults: { _controller: TroiswaBackBundle:Cart:delete }


troiswa_back_login:
    path:     /login
    defaults: { _controller: TroiswaBackBundle:Main:login }

troiswa_back_login_check:
    path:     /login_check

troiswa_back_logout:
    path:     /logout
