services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    troiswa_back.util:
        class: Troiswa\BackBundle\Util\Utility
        arguments: [%competences%, @doctrine.orm.entity_manager, "ceci est du texte"]
