services:
#    troiswa_back.example:
#        class: Troiswa\BackBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    troiswa_back.util:
        class: Troiswa\BackBundle\Util\Utility
        arguments: [%competences%, @doctrine.orm.entity_manager, "ceci est du texte"]

    troiswa_back.cart:
        class: Troiswa\BackBundle\Util\Cart
        arguments: [@doctrine.orm.entity_manager, @session]