<?php

namespace Troiswa\BackBundle\Repository;

/**
 * marqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{
}
