<?php

namespace Troiswa\BackBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllPerso()
    {
        //die("ok")
        //SELECT * == SELECT prod
        /*
        $query= $this->getEntityManager()
        ->createQuery("
        SELECT prod
        FROM WaBackBundle:Produit prod
        ");
        */

        $query= $this->createQueryBuilder("product")
        ->getQuery();

        // die(dump($query->getResult()));
        return $query->getResult();
    }

    public function findPerso($id)
    {

        $query= $this->createQueryBuilder("product")
        ->where('product.id = :idProd')
        ->setParameter("idProd", $id)
        ->getQuery();

        //die(dump($query->getSingleResult()));
        return $query->getSingleResult();



        /*Dans la clause WHERE idProd est une variable qui va contenir la valeur
        parametre id*/

        // _em = getEntityManager()
        /*$query= $this->_em->createQuery("
        SELECT prod
        FROM WaBackBundle:Produit prod

        WHERE prod.id= :idProd
        ")
        ->setParameter("idProd", $id);
        /*
        * permet d'avoir plusieurs arguments
        ->setParameters(
        [
        "idProd" => $id,
        ]
        );
        */

        return $query->getSingleResult();
    }

    public function findAllProdctCategory()
    {

        $query = $this->getEntityManager()
                      ->createQuery(
                          "SELECT prod, cat
                          FROM TroiswaBackBundle:Product prod
                          LEFT JOIN prod.categorie cat
                          "
                      );

        return $query->getResult();
    }


    public function findProductByQuantity($qty = 5)
    {
        //die("ok")
        //SELECT * == SELECT prod

        $query= $this->getEntityManager()
        ->createQuery("
        SELECT prod
        FROM TroiswaBackBundle:Product prod
        WHERE prod.quantity <= :qty
        ")
        ->setParameter('qty', $qty);

        return $query->getResult();
    }

}
